implement audit logs API
javadiscord/java-discord-api pull request #68
Opened 2024-04-20 17:53 UTC by tferdous17

**Describe the PR**

Finish implementing audit logs API and its sole endpoint:
- Get Guild Audit Log

**Checklist**
- [ ] This PR contains environment variables
- [ ] Documentation has been updated
- [ ] Tests have been added
- [ ] This PR contains breaking changes

2024-04-20 18:24 UTC, surajkumar commented
You're missing one of the APIs, it's got 2 not 1 :p 

`[GET /guilds/{guild.id}/audit-logs](https://discord.com/developers/docs/resources/audit-log#get-guild-audit-log)`

2024-04-20 18:24 UTC, surajkumar requested changes
[GET /guilds/{guild.id}/audit-logs](https://discord.com/developers/docs/resources/audit-log#get-guild-audit-log)

You're missing one!

2024-04-22 06:29 UTC, nateweisz approved these changes

2024-04-22 20:34 UTC, nateweisz approved these changes

2024-04-23 18:04 UTC, surajkumar approved these changes

2024-04-23 18:05 UTC, merged