Create wrappers over the DiscordRequest classes
javadiscord/java-discord-api pull request #86
Opened 2024-04-28 00:14 UTC by surajkumar

Created a bunch of wrappers over the DiscordRequest classes. 

TODOs:

- Finish the Channel requests
- Add the Guild requests

2024-04-29 20:27 UTC, nateweisz commented on models/src/main/java/com/javadiscord/jdi/core/models/message/StickerPack.java
> +        long sku_id,
Need's to use @JsonProperty and rename to skuId

2024-05-03 13:18 UTC, Taz03 requested changes

2024-05-03 13:18 UTC, Taz03 commented on api/src/main/java/com/javadiscord/jdi/core/api/builders/ModifyStageBuilder.java
> +    private final String channelId;
channelId string?

2024-05-03 13:18 UTC, Taz03 commented on api/src/main/java/com/javadiscord/jdi/core/api/utils/DiscordImageUtil.java
> +    private static final List<String> IMAGE_EXTENSIONS = Arrays.asList("jpg", "jpeg", "png", "gif");
um, this is out of scope but, List.of ?

2024-05-03 13:18 UTC, Taz03 commented on models/src/main/java/com/javadiscord/jdi/core/models/guild/Onboarding.java
> +        OnboardingMode mode) {}
@JsonProperty

2024-05-03 13:18 UTC, Taz03 commented on models/src/main/java/com/javadiscord/jdi/core/models/guild/PruneCount.java
> +public record PruneCount(int pruned) {}
@JsonProperty

2024-05-03 13:18 UTC, Taz03 commented on models/src/main/java/com/javadiscord/jdi/core/models/voice/VoiceRegion.java
> +        String id, String name, boolean optimal, boolean deprecated, boolean custom) {}
@JsonProperty

2024-05-03 13:18 UTC, Taz03 commented on api/src/main/java/com/javadiscord/jdi/core/api/builders/CreateMessageBuilder.java
> +    private Optional<Object> files; // TODO: Create File object
Make models before merging

2024-05-03 13:18 UTC, Taz03 commented on api/src/main/java/com/javadiscord/jdi/core/api/builders/StartThreadInForumOrMediaChannelBuilder.java
> +    private Optional<Object> files; // TODO: Create Files object
create models before merging

2024-05-03 18:29 UTC, Taz03 requested changes

2024-05-03 18:29 UTC, Taz03 commented on api/src/main/java/com/javadiscord/jdi/core/api/builders/ExecuteGithubCompatibleWebhookRequestBuilder.java
> +    public ExecuteGithubCompatibleWebhookRequestBuilder waits(Optional<Boolean> waits) {
fix

2024-05-03 18:29 UTC, Taz03 commented on api/src/main/java/com/javadiscord/jdi/internal/api/webhook/EditWebhookMessageRequest.java
> +        Optional<Object> files, // TODO: Create Model
make models before merging

2024-05-03 18:29 UTC, Taz03 commented on api/src/main/java/com/javadiscord/jdi/internal/api/webhook/ExecuteWebhookRequest.java
> +        Optional<Object> files, // TODO: Create model
make models before merging

2024-05-09 19:01 UTC, merged