81 implement guild template api
javadiscord/java-discord-api pull request #90
Opened 2024-05-05 10:55 UTC by notyourhabibti

Raised on behalf of Ashi:

This pull requests introduces the guild template api.

2024-05-05 10:57 UTC, surajkumar approved these changes

2024-05-05 11:23 UTC, Taz03 requested changes

2024-05-05 11:23 UTC, Taz03 commented on api/src/main/java/com/javadiscord/jdi/internal/api/guild_template/CreateGuildFromTemplateRequest.java
> +public record CreateGuildFromTemplateRequest(String templateCode, String name, String icon)
icon is optional

2024-05-05 11:23 UTC, Taz03 commented on api/src/main/java/com/javadiscord/jdi/internal/api/guild_template/DeleteGuildTemplateRequest.java
> +public record DeleteGuildTemplateRequest(
do u mean ModifyGuildTemplateRequest?

2024-05-05 11:23 UTC, Taz03 commented on api/src/main/java/com/javadiscord/jdi/internal/api/guild_template/DeleteGuildTemplate.java
> +public record DeleteGuildTemplate(long guildId, String templateCode) implements DiscordRequest {
postfix with request

2024-05-05 11:23 UTC, Taz03 commented on api/src/main/java/com/javadiscord/jdi/internal/api/guild_template/DeleteGuildTemplateRequest.java
> +        long guildId, String templateCode, String name, String description)
name and description is optional

2024-05-05 11:23 UTC, Taz03 commented on api/src/main/java/com/javadiscord/jdi/internal/api/guild_template/CreateGuildTemplateRequest.java
> +public record CreateGuildTemplateRequest(long guildId, String name, String description)
description is optional

2024-05-05 18:25 UTC, surajkumar approved these changes

2024-05-06 00:32 UTC, Taz03 requested changes

2024-05-06 00:32 UTC, Taz03 commented on api/src/main/java/com/javadiscord/jdi/internal/api/channel/StartThreadInForumOrMediaChannelRequest.java
revert

2024-05-06 00:32 UTC, Taz03 commented on api/src/main/java/com/javadiscord/jdi/internal/api/guild/GetGuildWidgetImageRequest.java
revert

2024-05-06 00:32 UTC, Taz03 commented on models/src/main/java/com/javadiscord/jdi/core/models/guild/AllowedMentionType.java
revert

2024-05-06 00:32 UTC, Taz03 commented on models/src/main/java/com/javadiscord/jdi/core/models/guild/AllowedMentions.java
revert

2024-05-06 00:32 UTC, Taz03 commented on models/src/main/java/com/javadiscord/jdi/core/models/guild/ForumMediaThreadMessageParam.java
revert

2024-05-06 00:32 UTC, Taz03 commented on models/src/main/java/com/javadiscord/jdi/core/models/guild/WidgetStyle.java
revert

2024-05-23 13:52 UTC, surajkumar commented
Closed in favour of https://github.com/javadiscord/java-discord-api/pull/122

2024-05-23 13:52 UTC, closed without merging